/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface SplitFactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "allSplits"
      | "createSplit"
      | "getAllSplits"
      | "getAllSplitsCount"
      | "getSplitsByOwner"
      | "getSplitsCountByOwner"
      | "isSplit"
      | "isValidSplit"
      | "splitsByOwner"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "SplitCreated"): EventFragment;

  encodeFunctionData(
    functionFragment: "allSplits",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createSplit",
    values: [AddressLike[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllSplits",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAllSplitsCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSplitsByOwner",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getSplitsCountByOwner",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isSplit",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isValidSplit",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "splitsByOwner",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "allSplits", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createSplit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllSplits",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllSplitsCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSplitsByOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSplitsCountByOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isSplit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isValidSplit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "splitsByOwner",
    data: BytesLike
  ): Result;
}

export namespace SplitCreatedEvent {
  export type InputTuple = [
    splitAddress: AddressLike,
    owner: AddressLike,
    recipients: AddressLike[],
    percentages: BigNumberish[],
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    splitAddress: string,
    owner: string,
    recipients: string[],
    percentages: bigint[],
    timestamp: bigint
  ];
  export interface OutputObject {
    splitAddress: string;
    owner: string;
    recipients: string[];
    percentages: bigint[];
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SplitFactory extends BaseContract {
  connect(runner?: ContractRunner | null): SplitFactory;
  waitForDeployment(): Promise<this>;

  interface: SplitFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  allSplits: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  createSplit: TypedContractMethod<
    [_recipients: AddressLike[], _percentages: BigNumberish[]],
    [string],
    "nonpayable"
  >;

  getAllSplits: TypedContractMethod<[], [string[]], "view">;

  getAllSplitsCount: TypedContractMethod<[], [bigint], "view">;

  getSplitsByOwner: TypedContractMethod<
    [owner: AddressLike],
    [string[]],
    "view"
  >;

  getSplitsCountByOwner: TypedContractMethod<
    [owner: AddressLike],
    [bigint],
    "view"
  >;

  isSplit: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  isValidSplit: TypedContractMethod<
    [splitAddress: AddressLike],
    [boolean],
    "view"
  >;

  splitsByOwner: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "allSplits"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "createSplit"
  ): TypedContractMethod<
    [_recipients: AddressLike[], _percentages: BigNumberish[]],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAllSplits"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getAllSplitsCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getSplitsByOwner"
  ): TypedContractMethod<[owner: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getSplitsCountByOwner"
  ): TypedContractMethod<[owner: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "isSplit"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isValidSplit"
  ): TypedContractMethod<[splitAddress: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "splitsByOwner"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  getEvent(
    key: "SplitCreated"
  ): TypedContractEvent<
    SplitCreatedEvent.InputTuple,
    SplitCreatedEvent.OutputTuple,
    SplitCreatedEvent.OutputObject
  >;

  filters: {
    "SplitCreated(address,address,address[],uint256[],uint256)": TypedContractEvent<
      SplitCreatedEvent.InputTuple,
      SplitCreatedEvent.OutputTuple,
      SplitCreatedEvent.OutputObject
    >;
    SplitCreated: TypedContractEvent<
      SplitCreatedEvent.InputTuple,
      SplitCreatedEvent.OutputTuple,
      SplitCreatedEvent.OutputObject
    >;
  };
}
